config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :tracks, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, :band_id, presence: true
  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true
  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :track_id, :user_id, :text, presence: true
  belongs_to :user
  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, presence: true
  belongs_to :album
  has_one :band, through: :album, source: :band
  has_many :notes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :session_token, :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token
  
  has_many :notes


  attr_reader :password

  def self.generate_session_token
    SecureRandom.base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    digest = BCrypt::Password.new(self.password_digest)
    digest.is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user == nil
    user.is_password?(password) ? user : nil
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_unless_logged_in

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    @album.update_attributes(album_params)

    @album.save!
    redirect_to album_url(@album)
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to bands_url
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end


private

  def album_params
    params.require(:album).permit(:title, :band_id, :live_album)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in(user)
    session[:session_token] = user.session_token
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def redirect_unless_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def redirect_if_logged_in
    redirect_to user_url(current_user) if logged_in?
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :redirect_unless_logged_in

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    @band.update_attributes(band_params)
    @band.save!
    redirect_to band_url(@band)
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def index
    @bands = Band.all
    render :index
  end

private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save
    redirect_to track_url(@note.track_id)
  end

  def destroy
    @note = Note.find(params[:id])
    return head(:forbidden) unless @note.user_id == current_user.id
    @note.destroy
    redirect_to track_url(@note.track_id)
  end

  private

  def note_params
    params.require(:note).permit(:text, :track_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new]


  def new
    render :new
  end

  def create
    user = User.find_by_credentials(session_params[:email], session_params[:password])
    if user.nil?
      flash[:errors] = ["We couldn't find that account"]
      redirect_to new_session_url
    else
      log_in(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :redirect_unless_logged_in

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    @track.update_attributes(track_params)
    @track.save!
    redirect_to track_url(@track)
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to bands_url
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end


private

  def track_params
    params.require(:track).permit(:name, :bonus, :album_id, :lyrics)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_unless_logged_in, only: [:show]
  before_action :redirect_if_logged_in, only: [:new]


  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end

  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    html = "<input type = 'hidden' name = 'authenticity_token' value = '#{form_authenticity_token}'>"
    html.html_safe
  end

  def ugly_lyrics(lyrics)
    return nil if lyrics.nil?
    lines = lyrics.split("\n")
    lines.map! {|line| line.chomp("\r")}
    html = "<pre>"

    lines.each do |line|
      html += "&#9835;" unless line.empty?
      html += " #{h(line)}\n"
    end

    html += "</pre>"
    html.html_safe
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% if album.errors.full_messages  %>
<% album.errors.full_messages.each do |msg|  %>
  <p style ="color:#ff7f7f"> <%= msg %> </p>
<% end end %>

<form action="<%= album.persisted? ? album_url(album.id) : albums_url %>" method="post">
  <% if album.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
<%= auth_token %>

<label for="title">Album Title</label>
 <input id = "title" type="text" name="album[title]"
        value = "<%= album.persisted? ? album.title : "" %>">  <br><br>

<label for="band">Band</label>
<select id="band" name="album[band_id]">
  <option disabled <%= album.band_id ? "" : "selected"%>>-- Please Select --</option>
  <% Band.all.each do |band| %>
    <option value= <%= band.id %>
      <%= album.band_id == band.id ? "selected" : ""%>>
      <%= band.name %></option>
  <% end %>
</select><br><br>

<label for="live">Live album?</label>
  <input id="live" type="radio" name="album[live_album]" value="true"
        <%= album.live_album ? "checked" : "" %> >Yes
  <input id="live" type="radio" name="album[live_album]" value="false"
        <%= album.live_album ? "" : "checked" %>  >No <br><br>


<input type="submit" value="Submit">

app/views/albums/edit.html.erb
<h2> edit yo album </h2>

<%= render 'form', album: @album %>

app/views/albums/new.html.erb
<h2> add an album </h2>

<%= render 'form', album: @album %>

app/views/albums/show.html.erb
<h3> Album details </h3>

<p> Title: <%= @album.title %> </p>
<p> Band: <%= link_to @album.band.name, band_url(@album.band_id) %> </p>
<p> <%= @album.live_album ? "This is a live album." : "" %> </p>

<%= link_to 'Edit Album', edit_album_url(@album) %>&nbsp;
&nbsp;
<%= link_to 'Delete Album', album_url(@album), method: :delete %>

<h3> Tracks </h3>
<ul>
<% @album.tracks.each do |track| %>
  <li> <%= link_to track.name, track_url(track) %></li>
<% end %>
</ul>

<%= link_to 'Add Track', new_track_url %>

app/views/bands/_band.html.erb
<li> <%= link_to band.name, band_url(band) %> </li>

app/views/bands/_form.html.erb
<% if band.errors.full_messages  %>
<% band.errors.full_messages.each do |msg|  %>
  <p style ="color:#ff7f7f"> <%= msg %> </p>
<% end end %>
<form action="<%= band.persisted? ? band_url(band.id) : bands_url %>" method="post">
  <% if band.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
<%= auth_token %>

<label for="name">Band Name</label>
 <input id = "name" type="text" name="band[name]"
        value = "<%= band.persisted? ? band.name : "" %>">  <br><br>


<input type="submit" value="Submit">

app/views/bands/edit.html.erb
<h2> edit yo band </h2>

<%= render 'form', band: @band %>

app/views/bands/index.html.erb
<h2> Bands! </h2>

<ul>
<%= render @bands %>
</ul>

<%= link_to 'Add Band', new_band_url %>

app/views/bands/new.html.erb
<h2> add a band </h2>

<%= render 'form', band: @band %>

app/views/bands/show.html.erb
<h3> Band details </h3>

<p> Name: <%= @band.name %> </p>

<%= link_to 'Edit Band', edit_band_url(@band) %>&nbsp;
&nbsp;
<%= link_to 'Delete Band', band_url(@band), method: :delete %>

<h3> Albums </h3>
<ul>
<% @band.albums.each do |album| %>
  <li> <%= link_to album.title, album_url(album) %></li>
<% end %>
</ul>

<%= link_to 'Add Album', new_album_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <style>
    body {background-color: grey;}
    h2   {font-family: courier; color: purple;}
    h3   {font-family: courier; color: purple;}
    h1   {font-family: courier; color: purple;}
    p    {font-family: courier; color: white;}
    label  {font-family: courier; color: white;}
    form  {font-family: courier; color: white;}
    a    {font-family: courier; color: white;}
    body {padding-left: 400px;}
</style>
</head>
<body>
<header>
  <h2> <%= link_to 'super cool music app', bands_url %>
  <% if current_user %>
    <%= button_to 'Log out', session_url, method: :delete %>
  <% else %>
    <%= button_to 'Log in', new_session_url, method: :get %>
  <% end %> </h2>
</header>
<br><br><br>


<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<p> Write a note </p>
<form action="<%= notes_url %>" method="post">
<%= auth_token %>
<textarea name="note[text]" rows="8" cols="80">  </textarea>
<input type="hidden" name="note[track_id]" value="<%= t_id %>"></input><br><br>
<input type="submit" value="Submit"></input>
</form>

app/views/notes/_note.html.erb
 <%= note.user.email %> <br>
 <%= note.text %>
 <% if note.user_id == current_user.id %>
  <%= button_to "Delete", note_url(note), method: :delete %>
  <br>
<% end %>

app/views/tracks/_form.html.erb
<% if track.errors.full_messages  %>
<% track.errors.full_messages.each do |msg|  %>
  <p style ="color:#ff7f7f"> <%= msg %> </p>
<% end end %>

<form action="<%= track.persisted? ? track_url(track.id) : tracks_url %>" method="post">
  <% if track.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
<%= auth_token %>

<label for="name">Track Name</label>
 <input id = "name" type="text" name="track[name]"
        value = "<%= track.persisted? ? track.name : "" %>">  <br><br>

<label for="album">Album</label>
<select id="album" name="track[album_id]">
  <option disabled <%= track.album_id ? "" : "selected"%>>-- Please Select --</option>
  <% Album.all.each do |album| %>
    <option value= <%= album.id %>
      <%= track.album_id == album.id ? "selected" : ""%>>
      <%= album.title %></option>
  <% end %>
</select><br><br>


<label for="bonus">Bonus track?</label>
<input id="bonus" type="radio" name="track[bonus]" value="true"
      <%= track.bonus ? "checked" : "" %> >Yes
<input id="bonus" type="radio" name="track[bonus]" value="false"
      <%= track.bonus ? "" : "checked" %>  >No <br><br>

<label for="lyrics">Lyrics:</label><br>
<textarea name="track[lyrics]" rows="8" cols="80"><%= track.lyrics ? track.lyrics : "" %></textarea><br><br>


<input type="submit" value="Submit">
</form>

app/views/tracks/edit.html.erb
<h2> edit yo track </h2>

<%= render 'form', track: @track %>

app/views/tracks/new.html.erb
<h2> add a track </h2>

<%= render 'form', track: @track %>

app/views/tracks/show.html.erb
<h3> Track details </h3>

<p> Title: <%= @track.name %> </p>
<p> Band: <%= link_to @track.band.name, band_url(@track.band) %> </p>
<p> Album: <%= link_to @track.album.title, album_url(@track.album_id) %> </p>
<p> <%= @track.bonus ? "This is a bonus track." : "" %> </p>

<p> Lyrics </p>
<p> <%= ugly_lyrics(@track.lyrics) %> </p>


<%= link_to 'Edit track', edit_track_url(@track) %>
&nbsp;
&nbsp;
<%= link_to 'Delete track', track_url(@track), method: :delete %>

<h3> Notes </h3>
<% @track.notes.each do |note| %>
<%= render 'notes/note', note: note %><br><br>
<% end %>



<%= render 'notes/form', t_id: @track.id %>

app/views/users/new.html.erb
<h2> sign up plz </h2>

<% if flash[:errors]  %>
<% flash[:errors].each do |msg|  %>
  <p style ="color:#ff7f7f"> <%= msg %> </p>
<% end end %>

<form action="<%= users_url %>" method="post">
<%= auth_token %>


<p>Email</p> <input type="text" name="user[email]"></input><br>
<p>Password</p> <input type="password" name="user[password]"></input><br><br>

<input type="submit" value="do it">

</form>

app/views/users/show.html.erb
<p> Hey. Your email is <%= @user.email %>. </p>